Add LP rewards farming template
Vikings-Tech/Smart-Contract-Templates pull request #5
Opened 2021-10-10 16:21 UTC by pauliax

2021-10-11 11:13 UTC, MysteriousAcadia requested changes
Looks good! Please make the necessary changes as suggested to improve readability.

2021-10-11 11:13 UTC, MysteriousAcadia commented on LPRewards/FarmController.sol
> +contract FarmController is OwnableUpgradeable {
Please add comments explaining the functions, parameters and the return values.
It should be easy for other developers to understand the usage.

You can refer to this article:
https://jeancvllr.medium.com/solidity-tutorial-all-about-comments-bc31c729975a

2021-10-16 08:22 UTC, pauliax commented
Updated with comments

2021-10-17 09:31 UTC, MysteriousAcadia approved these changes

2021-10-17 09:32 UTC, merged